apiVersion: kubernetes.crossplane.io/v1alpha1
kind: Object
metadata:
  name: wacamole-hello-deployment
spec:
  forProvider:
    manifest:
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: wacamole-hello
        namespace: myapp
        labels:
          app: wacamole-hello
      spec:
        replicas: 1
        selector:
          matchLabels:
            app: wacamole-hello
        template:
          metadata:
            labels:
              app: wacamole-hello
          spec:
            containers:
            - name: wacamole-hello
              image: javpaw/wacamole-hello:latest
              ports:
              - containerPort: 8000
              resources:
                requests:
                  memory: "64Mi"
                  cpu: "250m"
                limits:
                  memory: "128Mi"
                  cpu: "500m"
  providerConfigRef:
    name: kubernetes-provider
