apiVersion: v1
kind: Service
metadata:
  name: wacamole-hello
  namespace: myapp
spec:
  selector:
    app: wacamole-hello
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
  type: ClusterIP
